---
# 
# Author: Justin Quijano
# TELE36058 - Software Defined Networks
# Lab 2 - Ansible Tower/AWX
  - name: Configure R2's interfaces and OSPFv2
    hosts: R2
    gather_facts: false
    become: true

    tasks:
      - name: Enable R2's interfaces
        cisco.ios.ios_interfaces:
          config:
            - name: GigabitEthernet1/0
              description: WAN link to R1
              enabled: true 
            - name: GigabitEthernet0/0
              description: Used for sub-interface 
              enabled: true 
            - name: GigabitEthernet0/0.10
              description: Sub-interface for VLAN 10 (IT)
              enabled: true 
            - name: GigabitEthernet0/0.20
              description: Sub-interface for VLAN 20 (Servers)
              enabled: true 
            - name: GigabitEthernet2/0
              description: Used for sub-interface
              enabled: true
            - name: GigabitEthernet2/0.30
              description: Sub-interface for VLAN 30 (WebDev)
              enabled: true
            - name: GigabitEthernet2/0.40
              description: Sub-interface for VLAN 40 (Marketing)
              enabled: true

      - name: Assigning IP address on R2's interfaces
        cisco.ios.ios_l3_interfaces:
          config:
            - name: GigabitEthernet1/0
              ipv4:
              - address: 10.12.12.2/30
            - name: GigabitEthernet0/0.10
              ipv4:
              - address: 172.16.31.1/26
            - name: GigabitEthernet0/0.20
              ipv4:
              - address: 172.16.31.65/26
            - name: GigabitEthernet2/0.30
              ipv4:
              - address: 172.16.31.129/26
            - name: GigabitEthernet2/0.40
              ipv4:
              - address: 172.16.31.193/26
          state: merged

      - name: Configure OSPF 
        cisco.ios.ios_ospfv2:
          config:
            processes:
            - areas:
              - area_id: '0'
              network:
              - address: 10.12.12.0 
                wildcard_bits: 0.0.0.3
                area: '0'
              - address: 172.16.31.0
                wildcard_bits: 0.0.0.255
                area: '0'
              process_id: 1
          state: merged

      - name: Show OSPF and interface configuration
        ios_command: 
          commands:
          - show run | section ospf 
          - show ip interface brief | exclude unassigned
        register: output

      - name: print output
        debug:
          var: output.stdout_lines