---
  - name: Playbook to reboot servers
    vars_prompt:
      - name: "hostname"
        prompt: |
          Please enter the server name to reboot ('servers' targets all servers)
          - servers
          - dev01
          - dns01
          - dhcp01
          - filesrv01
        private: false

    hosts: "{{ hostname }}" 
    become: true
    gather_facts: false
    tasks:
      - set_fact:
          supplied_hostname: "{{ hostname }}"

      - name: Prompt user to confirm action before rebooting
        ansible.builtin.pause:
          prompt: "{{ item }}"
        with_items: |
          Warning: Proceed with reboot?
          Press ENTER to continue or CTRL + C to cancel...

      - name: Notify server reboot 
        ansible.builtin.debug:
          msg: Please allow 3-5 minute for the server to reboot. Rebooting server {{ supplied_hostname }}...

      - name: Reboot server 
        ansible.builtin.reboot:
        