---
  - name: Playbook to update and upgrade all servers
    vars:
      hostname: ""

    hosts: "{{ hostname }}" 
    become: true
    gather_facts: false
    tasks:
      - set_fact:
          supplied_hostname: "{{ hostname }}"

      - name: Run distribution upgrade
        ansible.builtin.apt:
          upgrade: dist
          update_cache: yes

      - name: Check if a reboot is required
        ansible.builtin.stat:
          path: /var/run/reboot-required
          get_md5: no
        register: reboot_required_file

      - name: Print if reboot is required 
        ansible.builtin.debug:
         msg: Reboot required on {{ supplied_hostname }}. Please run 'reboot_servers.yml'
        when: reboot_required_file.stat.exists == true
