---
# 
# Author: Justin Quijano
# TELE36058 - Software Defined Networks
# Lab 2 - Ansible Tower/AWX
  - name: Playbook to reboot servers
    vars:
      hostname: ""
    hosts: "{{ hostname }}" 
    become: true
    gather_facts: false
    tasks:

      - name: Notify server reboot 
        ansible.builtin.debug:
          msg: Please allow 3-5 minute for the server to reboot. Rebooting server {{ hostname }}...

      - name: Reboot server 
        ansible.builtin.reboot:
        